### ISSUE TITLE
Use compose with latest version of next js as env

### ISSUE THREAD

**Issue by ShintaroNippon** [JerryCauser/next-compose#3]
Hi there...
I have this code
and I'm using latest version of next js... 

```
const compose = require("next-compose");
const withCSS = require("@zeit/next-css");
const withSass = require("@zeit/next-sass");
const withImages = require("next-images");

module.exports = compose([
  withCSS,
  withSass,
  withImages,
  {
    env: {
      server: "http://localhost:3000"
    }
  }
]);

```

and I'm asking it is possible to use env with compose
because currently, I'm getting process env as undefined...!

Thanks in advance
Carlos Vieira

**Comment by matthewphiong** [comment]
@ShintaroNippon This is not supported by this plugin. Use [next-compose-plugins](https://github.com/cyrilwanner/next-compose-plugins) instead.

**Comment by JerryCauser** [comment]
I can add a possibility to mix result config with objects in array, but is it necessary? I am not sure, because you can use native JS assigning (via spread operator) to achieve your goal:

```javascript
module.exports = {
  env: { server: "http://localhost:3000" },
  ...compose([withCSS, withSass, withImages])
}
```

@satazor, @ShintaroNippon is it ok, or mixing inside composer looks better?
