### ISSUE TITLE
Not working with next-pwa

### ISSUE THREAD

**Issue by ArthurKnoep** [JerryCauser/next-compose#6]
Hi guys,

I don't know if it is me who is messing arround but I wasn't able to use next-compose with the plugin next-pwa, the configuration object is not correctly passed.

Here is my next.config.js

```javascript
const withPWA = require('next-pwa');
const withSass = require('@zeit/next-sass');
const compose = require('next-compose');
const cacheRule = require('./cache');

const pwaConfig = {
    pwa: {
        disable: false,
        dest: 'public',
        sw: 'sw.js',
        runtimeCaching: cacheRule,
    },
};
const sassConfig = {
    cssModules: true,
    cssLoaderOptions: {
        camelCase: true
    }
};

module.exports = compose([
    [withPWA, pwaConfig],
    [withSass, sassConfig],
])
```

After some time wondering why my next-pwa plugin was misconfigured, I've temporarly changed my `next.config.js` to directly export `withPWA(pwaConfig)` and after that, the plugin starts to work correctly. So I've started to investigate next-compose plugin.

After adding few `console.log`, I've discovered that the next-pwa plugin was misconfigured because it did not receive my configuration object (I've added a `console.log(pwa)` on this line https://github.com/shadowwalker/next-pwa/blob/master/index.js#L43). When using the direct export of withPWA, the `console.log` print the configuration object I've passed (my `pwaConfig` in my next.config.js) while when using next-compose the `console.log` print an empty object. 
It appears that the next-pwa plugin is receiving the plugin configuration through the `options` variable of the webpack function and the problem is that next-compose directly forward its own `options` object to the plugin to load. So, obviously the `pwaConfig` object is not inside.

I've managed to create a temporary fix in my `node_modules` folder, here is my updated `index.js` file:
```javascript
module.exports = plugins => ({
  webpack(config, options) {
    return plugins.reduce((config, plugin) => {
      let optCopy = Object.assign({}, options);
      if (plugin instanceof Array) {
        const [_plugin, ...args] = plugin
        plugin = _plugin(...args)
        optCopy.config = Object.assign(optCopy.config, ...args);
      }
      if (plugin instanceof Function) {
        plugin = plugin()
      }
      if (plugin && plugin.webpack instanceof Function) {
        return plugin.webpack(config, options)
      }
      return config
    }, config)
  },

  // ..., the rest of the file is the same
})
```

If that is of any help, here are the versions I use:
next: 9.5.5
next-pwa: 3.1.5
next-compose: 0.0.2

Is my bug a real bug or is there something I've done wrong ?

**Comment by JerryCauser** [comment]
I think it is trouble in next-pwa. I looked at their code and they destruct `options` to get `config` and after that pick `pwa` from it.

If we check next.js  `next.config.js` docs we will see nothing about `config` field in `options`. 
https://github.com/vercel/next.js/blob/canary/docs/api-reference/next.config.js/custom-webpack-config.md

**Comment by ArthurKnoep** [comment]
Ok, that's weird.

I've tried with another plugin (https://github.com/cyrilwanner/next-compose-plugins) and it seems to be working correctly
